### ISSUE TITLE
Error when opening a new prompt on top of exising prompt

### ISSUE THREAD

**Issue by tahajahangir** [trentrichardson/jQuery-Impromptu#46]
Currently, impormptu does not support opening new prompt on top of another prompt.
See: http://jsfiddle.net/kj66j6wa/1/

Note the code works fine in impromptu 3.1: http://jsfiddle.net/kj66j6wa/2/

**Comment by trentrichardson** [comment]
@tahajahangir @Zalmoxisus These changes are now in the master branch as version 6.0.0.  I'm going to close this issue, but please re-open or create a new issue if you have problems.
