### ISSUE TITLE
Effect ignored when closing non-persistant prompt

### ISSUE THREAD

**Issue by javl** [trentrichardson/jQuery-Impromptu#53]
Enhancement

When no effect is set for showing a non-persistent overlay, there is still a fast fadeOut effect used when closing the overlay by clicking anywhere else in the screen. Maybe the close event can also use the opts.show effect? (or maybe a separate opts.hide effect)

**Comment by trentrichardson** [comment]
This has been merged with master in the new 6.0 release.  I'm going to close this but if you have issues jsut re-open.
