### ISSUE TITLE
Opening a new prompt on top of existing prompt, creates a hidden extra element

### ISSUE THREAD

**Issue by tahajahangir** [trentrichardson/jQuery-Impromptu#60]
See: http://jsfiddle.net/kj66j6wa/14/
Second prompt is also added in `jqistates` of first prompt.

**Comment by trentrichardson** [comment]
Thanks for the bug report.  I do see the issue you're referring to and am investigating it.

**Comment by trentrichardson** [comment]
This should now be working properly in the dev branch with commit b8821f6 referenced above.  Thanks for the bug report!
