### ISSUE TITLE
How can I open a prompt in a certain state?

### ISSUE THREAD

**Issue by uusijani** [trentrichardson/jQuery-Impromptu#61]
Sorry if this is obvious, but how can I open a multiple-state prompt in a specific state other than the first one in the states object? In other words, in the first statesdemo example, how can I open the prompt in state1 instead of state0?

I'm working on a login/logout/registration form with each of the three as a separate state and would like to start the prompt in either the "log in" or "log out" state depending on whether the user is currently logged in or not.

(I'm trying to work out the solution reading Impromptu's source code, but figured I'd also pose this question here for others like me to find in the future.)

**Comment by trentrichardson** [comment]
Hey @uusijani This is a very good question, and I there actually isn't directly a way to do this outside of making the first state in your array the one you open first.  I can definitely see this being an option like "initialState" or something.  This would take place around line 369 in the src folder:

```js
var $firstState = t.jqi.find('.'+ opts.prefix +'states .'+ opts.prefix +'state').eq(0);
t.goToState($firstState.data('jqi-name'));
```

So we might could change it to either look for a string for state name, or number for index (the current method)

```js
t.goToState(
	isNaN(opts.initialState) ? opts.initialState : 
		t.jqi.find('.'+ opts.prefix +'states .'+ opts.prefix +'state').eq(opts.initialState)
);
```

The option would also need to be added the the defaults object and default to 0.  You would then call it like:

```js
$.prompt(states, { initialState: 'my-state-name' });
```

I will try to update the dev branch with this as I it would be a great addition.  Thanks!

**Comment by uusijani** [comment]
Hey @trentrichardson, and thanks for the response! The best I could figure in the meantime was to initialize the prompt differently in each branch, like so:

    if (user.isSignedIn) {
        states = {
            signOut: states.signOut,
            signIn: states.signIn,
            register: states.register
        };
    } else {
        states = {
            signIn: states.signIn,
            signOut: states.signOut,
            register: states.register
        };
    }
    thePrompt = $.prompt(states);

But it's definitely better to have true support for this in the extension itself. Excellent!

**Comment by trentrichardson** [comment]
@uusijani This was the first change to the dev branch since the last stable release, so it should be pretty stable if this change works.  This chage is located in the dev branch:

https://github.com/trentrichardson/jQuery-Impromptu/tree/dev

**Comment by uusijani** [comment]
@trentrichardson I've just tested the branch with the change and it's working perfectly.
