### ISSUE TITLE
How to load content via ajax

### ISSUE THREAD

**Issue by minhcanhdn** [trentrichardson/jQuery-Impromptu#63]
Do you have any plane to build load content via ajax future?

**Comment by trentrichardson** [comment]
There are no current plans for it. I can't say I'd be against it if it were well thought out, but I'd as much interested in simpler integration with templating (when ajax requests return ajax or other data)

**Comment by minhcanhdn** [comment]
Thanks @trentrichardson, more question. How to set size for modal?
