### ISSUE TITLE
Can't get Enter keypress to click "OK"

### ISSUE THREAD

**Issue by winternet-studio** [trentrichardson/jQuery-Impromptu#65]
I have a prompt with a Cancel and OK button (index 0 and 1 respectively). It has no form fields in it. When I press Enter it ALWAYS assumes I'm pressing Cancel, regardless of the options focus and defaultButton.

I have tracked it down to line 321 in the source, in the first condition where you have: $tgt.is('textarea,.'+opts.prefix+'button')  - this evaluates to true because focus is indeed on the button already. But I don't understand why you require this to be false to trigger the click?!

Same in both Chrome v43 and Firefox v39.

**Comment by trentrichardson** [comment]
Sorry for the delay here.  Are you setting the `focus` or `defaultButton` options?

**Comment by winternet-studio** [comment]
Sorry, it's working now when I try again. Case closed.
