### ISSUE TITLE
Callback function

### ISSUE THREAD

**Issue by pricejt** [trentrichardson/jQuery-Impromptu#69]
Any idea why this is not calling my callback function. I am pretty sure this used to work. 

```
if(content == 'Success') {
                $.prompt('Success!<br />Your account has been created. You can now log      on.',{callback: redirectFunction});

                function redirectFunction()
                {
                    window.location = 'Index.htm';
                }
                }
```

**Comment by trentrichardson** [comment]
I know this is an old issue, but the newer versions no longer use "callback" as it was to ambiguous to when it was called in the event list. Now you would pass "close" or "submit" options as this function.
