### ISSUE TITLE
html option text?

### ISSUE THREAD

**Issue by asadghazanfary** [trentrichardson/jQuery-Impromptu#71]
how can dynamically my html content in html option when call sate with method gotostate()?

**Comment by trentrichardson** [comment]
Sorry for the delay here.  You can use $.prompt.getState(statename) to return a jquery object of the state.  From there you can use .find('.jqimessage').html('...content...');

``` js
$.prompt.getState(statename).find('.jqimessage').html('<p>my html..</p>');
```
