### ISSUE TITLE
In new version $.prompt("") is not working, must call $.prompt(" ") ?

### ISSUE THREAD

**Issue by Rupenbritz** [trentrichardson/jQuery-Impromptu#73]
Greetings, me again. We use impromptu in our web based tool and its great too work with!
As you know I was "forced" too updated to the newest version of impromptu too fix an IE bug.

However this new update (compared too the old 2013 version) brought upon a change in how the prompts are called.

Usually we build up our prompts as such;

var html = ""; //pre-built html
$.prompt("", {
                        title: "Add Media",
                        buttons: { "Close":false },
                        loaded: function () {  
                          $(this).find('.jqimessage').append(html);
                          $(window).resize();
                        }
                    });

As you noticed we call $.prompt(""), and later append onto it.
The new version does not allow "empty" prompts, and we must add a blank space

$.prompt(" "), and then append to it. Is this intended?

//Alex

**Comment by trentrichardson** [comment]
I don't see right off where in the code it should act this way, so it may be a bug.  

However if you need dynamic html a better approach to do this would be to pass a function that returns a string to the html option:

``` js
$.prompt([{
    title: "Add Media",
    buttons: { "Close":false },
    html: function(){ 
        return 'my computed html';
    },
    loaded: function(){
       $(window).resize();
     }
}]);
```

This would be less like a "hack" and the function will get computed every time the state is shown.

**Comment by Rupenbritz** [comment]
Oh maybe you dont even need to pass the string then?

**Comment by trentrichardson** [comment]
Correct, but notice the array brackets around the options object.  It basically creates a state.  There is actually an issue with the above example.  I passed the loaded callback to the state, it should be to the options:

``` js
$.prompt(
    [
        {
            title: "Add Media",
            buttons: { "Close":false },
            html: function(){ 
                return 'my computed html';
            }
        }
    ],
    {
        loaded: function(){
           $(window).resize();
         }
    }
);
```
