### ISSUE TITLE
Webjar License Error

### ISSUE THREAD

**Issue by iRhysBradbury** [trentrichardson/jQuery-Impromptu#74]
Hey, I would like to use this lib as a webjar. 
I am currently receiving this error when trying to deploy this repo as a webjar:
`Failed! All attempts to determine a license have been exhausted. The bower.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo. This problem will likely need to be resolved by working with the library maintainers directly. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: jquery-impromptu`

For this to be able happen change filename:

`MIT-LICENSE.txt` -> `LICENSE.txt` or `license.txt`

and add to `bower.json`:

`"license": "MIT"`

Love the lib btw!

Thanks - Rhys

**Comment by iRhysBradbury** [comment]
Love the lib btw!

**Comment by trentrichardson** [comment]
Sorry for the delay on this. I will try to update it.

**Comment by trentrichardson** [comment]
I've merged this to master and created a new release 1.6.3

**Comment by iRhysBradbury** [comment]
Thank you! 👍
